# Start from the Microsoft's Node.js & TypeScript image
FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

# Install the .NET 6 SDK
RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y apt-transport-https \
    && apt-get update \
    && apt-get install -y dotnet-sdk-6.0
