name: Build and Deploy to Harbor

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, zvaris]  # Nutzt deinen Runner statt ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Harbor
      run: |
        echo "${{ secrets.HARBOR_PASSWORD }}" | \
        docker login ${{ secrets.HARBOR_REGISTRY }} \
        -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin
        
    - name: Build and push Docker image to Harbor
      uses: docker/build-push-action@v5
      with:
        context: ./website-ui
        push: true
        tags: |
          ${{ secrets.HARBOR_REGISTRY }}/mmartin/website-michael-martin-ui:${{ github.sha }}
          ${{ secrets.HARBOR_REGISTRY }}/mmartin/website-michael-martin-ui:latest
        platforms: linux/amd64  # Nur amd64, da self-hosted Runner
        cache-from: type=registry,ref=${{ secrets.HARBOR_REGISTRY }}/mmartin/website-michael-martin-ui:cache
        cache-to: type=registry,ref=${{ secrets.HARBOR_REGISTRY }}/mmartin/website-michael-martin-ui:cache,mode=max
        
    - name: Cleanup local images
      run: |
        docker system prune -f
