name: Build and Deploy to Harbor
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: [self-hosted, zvaris]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to Harbor (before Buildx!)
      run: |
        echo "${{ secrets.HARBOR_PASSWORD }}" | \
        docker login https://${{ secrets.HARBOR_REGISTRY }} \
        -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        config-inline: |
          [registry."${{ secrets.HARBOR_REGISTRY }}"]
            http = false
            insecure = false
        
    - name: Build and push Docker image to Harbor
      uses: docker/build-push-action@v5
      with:
        context: ./website-ui
        push: true
        tags: |
          ${{ secrets.HARBOR_REGISTRY }}/mmartin/website-michael-martin-ui:${{ github.sha }}
          ${{ secrets.HARBOR_REGISTRY }}/mmartin/website-michael-martin-ui:latest
        platforms: linux/amd64
        cache-from: type=registry,ref=${{ secrets.HARBOR_REGISTRY }}/mmartin/website-michael-martin-ui:cache
        cache-to: type=registry,ref=${{ secrets.HARBOR_REGISTRY }}/mmartin/website-michael-martin-ui:cache,mode=max
    
    - name: Trigger Watchtower Update
      run: |
        curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" \
             -X POST http://${{ secrets.WATCHTOWER_BASEURL }}/v1/update
        
    - name: Cleanup local images
      run: |
        docker system prune -f
